version: "3.3"

services:
  item-service:
    build: item/
    image: automacao/item-service
    depends_on:
      - mongo
    ports:
      - 8091:8091
    environment:
      SPRING_PROFILES_ACTIVE: docker

  tag-service:
    build: tag/
    image: automacao/tag-service
    depends_on:
      - mongo
    ports:
      - 8092:8092
    environment:
      SPRING_PROFILES_ACTIVE: docker

  mongo:
    image: mongo
    restart: always
    ports:
    - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: services
      MONGO_NON_ROOT_USERNAME: user
      MONGO_NON_ROOT_PASSWORD: password

  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root