server:
  port: ${PORT:8091}

spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/item_db
    username: root
    password: root
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      key-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    consumer:
      enable-auto-commit: false
      group-id: item-service
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      client-id: 1
      properties:
        specific.avro.reader: true
      key-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
    listener:
      ack-mode: manual
    properties:
      schema.registry.url: 'http://localhost:8081'

events:
  item:
    created: item_created

