server:
  port: ${PORT:8091}

spring:
  r2dbc:
    url: r2dbc:mysql://mysql:3306/item_db
    username: item
    password: item
  kafka:
    bootstrap-servers: kafka-broker:29092
    properties:
      schema.registry.url: 'http://schema-registry:8081'
