server:
  port: 8092

spring:
  datasource:
    username: tag
    password: tag
    url: jdbc:mysql://localhost:3306/tag_db
  jackson:
    default-property-inclusion: non_null
    property-naming-strategy: SNAKE_CASE
    time-zone: UTC
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        generate_statistics: true
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 1000
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      key-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    consumer:
      enable-auto-commit: false
      group-id: tag-service
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      key-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      client-id: 1
      properties:
        specific.avro.reader: true
    listener:
      ack-mode: manual
    properties:
      schema.registry.url: 'http://localhost:8081'

services:
  item: http://localhost:8091/items
